stages:
 - build

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
 - 'choco install -y netfx-4.8-devpack'
 - 'dotnet restore .\AeroCtl.UI\'

build:
  tags:
   - shared-windows
   - windows
   - windows-1809
  stage: build
  script:
   - 'dotnet build .\AeroCtl.UI\ --no-incremental'
   - 'dotnet publish .\AeroCtl.UI\ --configuration Release'
   - '7z a AeroCtl.7z .\AeroCtl.UI\bin\Release\net48\publish\*'
  artifacts:
    paths:
     - AeroCtl.7z
    expire_in: 30 days
