stages:
 - build

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
 - 'choco install -y dotnet-5.0-sdk'

build:
  tags:
   - shared-windows
   - windows
   - windows-1809
  stage: build
  script:
   - 'dotnet publish .\AeroCtl.UI\ --configuration Release --runtime win-x64 --no-self-contained'
   - '7z a AeroCtl.7z .\AeroCtl.UI\bin\Release\net5.0-windows\win-x64\publish\*'
  artifacts:
    paths:
     - AeroCtl.7z
    expire_in: 30 days
